/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import dao.PlaceDAO;
import entites.Place;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class PlaceForm extends javax.swing.JInternalFrame {

    private PlaceDAO pl;
    private DefaultTableModel model;
    static int numero;
    // private Object tableplace;
    // private Object p;
    
    /**
     * Creates new form PlaceForm
     */
    public PlaceForm() {

        initComponents();
        pl = new  PlaceDAO();
        this.setTitle("Gestion des Places");
        
        // On récupère le modèle de la JTable créée par initComponents
        model = (DefaultTableModel) tableplace.getModel();
        load();
    }
    
    void load(){
        model.setRowCount(0);
        for(Place p : pl.findAll())
            model.addRow(new Object[]{
                    p.getNumero(),
                    p.getType(),
                    p.getStatut(),
                    p.getTarifHoraire()
            });
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableplace = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JLabel();
        txtType = new javax.swing.JLabel();
        txtStatut = new javax.swing.JLabel();
        txtTarif = new javax.swing.JLabel();
        jtype = new javax.swing.JComboBox();
        jstatut = new javax.swing.JComboBox();
        jnumero = new javax.swing.JTextField();
        jtarif = new javax.swing.JTextField();
        btnajouter = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();
        btnmodifier = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tableaux des infos"));

        tableplace.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "type", "statut", "tarifHoraire"
            }
        ));
        tableplace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableplaceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableplace);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1)
                .addGap(42, 42, 42))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Place"));

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumero.setText("Numero :");

        txtType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtType.setText("Type :");

        txtStatut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStatut.setText("Statut :");

        txtTarif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTarif.setText("Tarif (DH/H) :");

        jtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto", "Moto", "PMR" }));
        jtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtypeActionPerformed(evt);
            }
        });

        jstatut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libre", "Occupee" }));

        jnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnumeroActionPerformed(evt);
            }
        });

        jtarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtarifActionPerformed(evt);
            }
        });

        btnajouter.setText("Ajouter");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });

        btnsupprimer.setText("Supprimer");
        btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimerActionPerformed(evt);
            }
        });

        btnmodifier.setText("Modifier");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jtarif))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtStatut, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jstatut, 0, 163, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jnumero))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jstatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtStatut)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtTarif))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jtarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnumeroActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
        // TODO add your handling code here:
        try{
            int numero = Integer.parseInt(jnumero.getText());
            String type = jtype.getSelectedItem().toString();
            String statut = jstatut.getSelectedItem().toString();
            Double tarif = Double.parseDouble(jtarif.getText());

            // creation d'objet Entite
            entites.Place p = new entites.Place(numero, type, statut, tarif);

            // la creation de l'objet Place
            if(pl.create(p)) {

                // msg de succes
                javax.swing.JOptionPane.showMessageDialog(this, "La Place numero "+ numero + "a ete ajoutee avec succes!"); 

                load(); //  recharge le tableau immédiatement
                //  vider les champs après l'ajout
                jnumero.setText("");
                jtarif.setText("");
            }
            else {
                 javax.swing.JOptionPane.showMessageDialog(this, "Erreur : Impossible d'ajouter la place. Vérifiez si le numéro existe déjà.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
             javax.swing.JOptionPane.showMessageDialog(this, "Veuillez saisir des valeurs numeriques valides pour le numero et le tarif", "Format incorrect", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnajouterActionPerformed

    private void btnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimerActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vous bien suprimer cette place?");
        if (reponse == 0){
            pl.delete(numero);
            load();
        }
        
    }//GEN-LAST:event_btnsupprimerActionPerformed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        // TODO add your handling code here:
        // 1. On récupère les valeurs actuelles des champs (ce que l'utilisateur a modifié)
        int num = Integer.parseInt(jnumero.getText());
        String ty = jtype.getSelectedItem().toString();
        String st = jstatut.getSelectedItem().toString();
        double tr = Double.parseDouble(jtarif.getText());

        // 2. On crée l'objet 'p' (C'est ça le fameux "p" !)
        entites.Place p = new entites.Place(num, ty, st, tr);

        // 3. On envoie cet objet à la méthode update
        if(pl.update(p)){
            load(); // Recharge le tableau

            // Utilise showMessageDialog pour une simple info (Confirm c'est pour Oui/Non)
            JOptionPane.showMessageDialog(this, "Modification réussie !");

            // On déverrouille le numéro pour un futur ajout
            jnumero.setEditable(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Erreur lors de la modification.");
        }
        
    }//GEN-LAST:event_btnmodifierActionPerformed

    private void jtarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtarifActionPerformed

    private void jtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtypeActionPerformed

    private void tableplaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableplaceMouseClicked
        // TODO add your handling code here:
        int row = tableplace.getSelectedRow();
        if(row != 1){
         numero = Integer.parseInt(model.getValueAt(tableplace.getSelectedRow(), 0).toString());
         jnumero.setText(model.getValueAt(tableplace.getSelectedRow(),0).toString());
         jtype.setSelectedItem(model.getValueAt(tableplace.getSelectedRow(), 1).toString());
         jstatut.setSelectedItem(model.getValueAt(tableplace.getSelectedRow(), 2).toString());
         jtarif.setText(model.getValueAt(tableplace.getSelectedRow(),3).toString());
         
         jnumero.setEditable(false);
        }
        
    }//GEN-LAST:event_tableplaceMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jnumero;
    private javax.swing.JComboBox jstatut;
    private javax.swing.JTextField jtarif;
    private javax.swing.JComboBox jtype;
    private javax.swing.JTable tableplace;
    private javax.swing.JLabel txtNumero;
    private javax.swing.JLabel txtStatut;
    private javax.swing.JLabel txtTarif;
    private javax.swing.JLabel txtType;
    // End of variables declaration//GEN-END:variables
}
