/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.StationnementDAO;
import entites.Stationnement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author T480s
 */
public class StationnementForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form StationnementForm
     */
    // 1. Déclarer le DAO et le modèle ici
    private StationnementDAO sdao = new StationnementDAO();
    private DefaultTableModel model;
    
    
    public StationnementForm() {
        initComponents();
        
        // 2. Initialiser le modèle
        model = (DefaultTableModel) tableStationnement.getModel(); // Assure-toi que le nom de ta table est correct
        load(); // Charge les données au démarrage
    }
    
    void load() {
        model.setRowCount(0); // Vide le tableau
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        for (Stationnement s : sdao.findAll()) {
            // Gérer l'affichage des valeurs nulles (si le véhicule est encore dans le parking)
            String dateS = (s.getDateSortie() == null) ? "En cours" : sdf.format(s.getDateSortie());
            String montant = (s.getMontant() == 0.0) ? "-" : String.valueOf(s.getMontant());

            model.addRow(new Object[]{
                s.getId(), s.getNumero(), s.getMatricule(),
                sdf.format(s.getDateEntree()), dateS, montant
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEntree = new javax.swing.JButton();
        btnSortie = new javax.swing.JButton();
        txtMatricule = new javax.swing.JTextField();
        txtNumeroPlace = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStationnement = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Matricule :");

        jLabel2.setText("Num de Place :");

        btnEntree.setBackground(new java.awt.Color(255, 153, 153));
        btnEntree.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnEntree.setText("Enregistrer Entrée");
        btnEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntreeActionPerformed(evt);
            }
        });

        btnSortie.setBackground(new java.awt.Color(255, 153, 153));
        btnSortie.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSortie.setText("Enregistrer Sortie");
        btnSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortieActionPerformed(evt);
            }
        });

        txtNumeroPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroPlaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(txtMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addComponent(txtNumeroPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnEntree)
                .addGap(26, 26, 26)
                .addComponent(btnSortie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntree)
                    .addComponent(btnSortie))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableStationnement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Num de place", "Matricule", "Date Entree", "date Sortie", "Montant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableStationnement);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroPlaceActionPerformed

    private void btnSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortieActionPerformed
        // TODO add your handling code here:
        int row = tableStationnement.getSelectedRow();
        if (row != -1) {
            int id = Integer.parseInt(model.getValueAt(row, 0).toString());

            // Vérifier si le véhicule est bien encore dans le parking (dateSortie == null)
            if (!model.getValueAt(row, 4).toString().equals("En cours")) {
                JOptionPane.showMessageDialog(this, "Ce véhicule est déjà sorti.");
                return;
            }

            Stationnement s = new Stationnement();
            s.setId(id);

            // Le DAO calcule automatiquement le montant et la date
            sdao.update(s);

            load(); // Rafraîchit pour voir le résultat
            JOptionPane.showMessageDialog(this, "Sortie enregistrée !");
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un stationnement.");
        }
    }//GEN-LAST:event_btnSortieActionPerformed

    private void btnEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntreeActionPerformed
        // TODO add your handling code here:
        try {
            int num = Integer.parseInt(txtNumeroPlace.getText());
            String mat = txtMatricule.getText();

            // Date actuelle générée automatiquement
            Stationnement s = new Stationnement(num, mat, new java.util.Date(), null, 0.0);

            if (sdao.create(s)) {
                load(); // Rafraîchit le tableau
                JOptionPane.showMessageDialog(this, "Véhicule entré !");
            } else {
                JOptionPane.showMessageDialog(this, "Erreur : Place occupée ou inexistante.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur de saisie : Vérifiez le numéro de place.");
        }
        
    }//GEN-LAST:event_btnEntreeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntree;
    private javax.swing.JButton btnSortie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableStationnement;
    private javax.swing.JTextField txtMatricule;
    private javax.swing.JTextField txtNumeroPlace;
    // End of variables declaration//GEN-END:variables
}
